config/routes.rb
Rails.application.routes.draw do

  get "about", to: "about#index", as: :about

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete 'logout', to: 'sessions#destroy'

  get 'password', to: 'passwords#edit', as: :edit_password
  patch "password", to: "passwords#update"

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'

  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get '/auth/twitter/callback', to: 'omniauth_callbacks#twitter'

  resources :twitter_accounts
  resources :tweets
  
  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 24.hours.from_now
  end

  def published?
    tweet_id?
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def publish_to_twitter!
    # Make post request to Twitter API for publish the tweet, and then store the response to tweet object
    tweet = twitter_account.client.update(body)

    # Update the tweet id field in the record to tweet id we get in response
    update(tweet_id: tweet.id)
  end
  
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user

  has_many :tweets, dependent: :destroy

  validates :username, uniqueness: true


  def client
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :twitter_accounts
    has_many :tweets

    has_secure_password
    
    validates :email, presence: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to login_path, alert: "Anda harus login terlebih dahulu!" if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
      # flash.now[:notice] = 'Logged in Successfully'
      # flash.now[:alert] = 'Invalid Email or Password'
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
    def twitter
        Rails.logger.info auth

        # Code ini akan mencari user di database dengan username yang sama dari response, jika ada ambil, namun jika tidak buatkan records baru dengan username tersebut.
        twitter_accounts = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize

        # Otomatis object twitter_accounts akan memiliki user entah itu user lama, ataupun user baru. Kemudian perbarui data dengan data dari response
        twitter_accounts.update(
            name: auth.info.name,
            username: auth.info.nickname,
            image: auth.info.image,
            token: auth.credentials.token,
            secret: auth.credentials.secret
        )

        redirect_to twitter_accounts_path, notice: "Successfully connect to Twitter"
    end

    def auth
        request.env['omniauth.auth']
    end
    
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
        
    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            PasswordMailer.with(user: @user).reset.deliver_now
        end
        redirect_to root_path, notice: "Email telah terkirim"
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to root_path, alert: "Token reset password salah atau telah expired!"
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to root_path, notice: "Password berhasil direset!"
        else
            render :edit
        end
    end

    private
    
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

    before_action :require_user_logged_in!

    def edit
    end

    def update
        if Current.user.update(password_parrams)
            redirect_to edit_password_path, notice: "Password changed successfully!"
        else
            render :edit
        end
    end
    
    private

    def password_parrams
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully created account"
        else 
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Login Successfully!"
        else
            flash[:alert] = "User or Password Invalid!"
            redirect_to login_path
       end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged Out"
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_tweet, only: [:edit, :update, :destroy]

    def index
        @tweets = Current.user.tweets
        @published_tweets = Current.user.tweets.where.not(tweet_id: nil)
        @unpublished_tweets = Current.user.tweets.where(tweet_id: nil)
    end

    def new
        @tweet = Tweet.new
    end

    def create
        @tweet = Current.user.tweets.new(tweet_params)
        if @tweet.save
            redirect_to tweets_path, notice: "Tweet was scheduled successfully"
        else
            render :new
        end
    end

    def edit
        
    end

    def update
        if @tweet.update(tweet_params)
            redirect_to tweets_path, notice: "Tweet was updated successfully!"
        else
            render :edit
        end
    end

    def destroy
        @tweet.destroy
        redirect_to tweets_path, alert: "Tweet was deleted successfully!"
    end

    private

    def tweet_params
        Rails.logger.info params
        params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
    end

    def set_tweet
        @tweet = Current.user.tweets.find(params[:id])
    end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_twitter_account, only: [:destroy]

    def index
        @twitter_accounts = Current.user.twitter_accounts
    end

    def destroy
        @twitter_accounts = Current.user.twitter_accounts.find(params[:id])
        @twitter_accounts.destroy
        redirect_to twitter_accounts_path, alert: "Account @#{@twitter_accounts.username} successfully deleted!"
    end

    def set_twitter_account
        @twitter_accounts = Current.user.twitter_accounts.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_class(link_path)
        current_page?(link_path) ? "active" : ""
    end
end

app/views/about/index.html.erb
<div class="d-flex align-items-center justify-content-center py-5 px-3 border rounded border-primary my-4">
    <h1>About Us!</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>ScheduledTweets</title>
  <meta name="viewport" content="width=device-width,initial-sale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= render partial: "shared/navbar" %>
  <div class="container">
    <%= render partial:"shared/flash" %>
    <%= yield %>
    
  </div>
</body>

</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center py-5 px-3 border rounded border-primary my-4">
    <h1>Twitter Accounts</h1>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |f|%>

    <% if f.object.errors.any? %>
        <div class="alert alert-danger">
            <% f.object.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <% end %>
    
    <div class="mb-3">
        <%= f.label :password %>
        <%= f.password_field :password , class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation , class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= f.submit "Reset Password", class:"btn btn-primary"%>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your Password?</h1>

<%= form_with url: password_reset_path do |f|%>
    <div class="mb-3 mt-5">
        <%= f.label :email %>
        <%= f.text_field :email , class: "form-control", placeholder: "name@example.com"%>
    </div>
    <div class="mb-3">
        <%= f.submit "Send Email", class:"btn btn-primary"%>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>


<% if flash[:alert]%>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_form_error.html.erb
    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link <%= active_class(root_path) %>" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class: "nav-link " + active_class(tweets_path) %>
        </li>
        <li class="nav-item">
          <%= link_to "Twitter Account", twitter_accounts_path, class: "nav-link " + active_class(twitter_accounts_path) %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link " + active_class(about_path) %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <% if Current.user %>
            <%= link_to  Current.user.email, edit_password_path, class: "nav-link"%>
            <li class="nav-item">
              <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-danger" %>
            </li>
          <% else %>
            <%= link_to  "Sign Up", sign_up_path, class: "btn btn-outline-success" %>
            <%= link_to  "Login", login_path, class: "btn btn-success" %>
          <% end %>  
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/tweets/_form.html.erb
<div class="d-flex flex-column p-3 border rounded my-4">
    <%= form_with model: tweet, local: true, data: { turbo: false } do |form|%>

        <%= render "shared/form_error", form: form %>
        <%= form.label :twitter_account_id, "Username" %>
        <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {class: "form-control my-2"} %>
        <%# <%= form.text_field :twiiter_account_id, class: "form-control my-2" %>
        
        <%# <%= link_to "Connect a Twitter Account", "/auth/twitter", method: :post, data: {turbo: "false"}, class: "btn btn-outline-primary mb-3" %>

        <%= form.label :body, "Tweets" %>
        <%= form.text_area :body, class: "form-control my-2" %>

        <%= form.label :publish_at, "Publish Datetime" %>
        <div class="form-control my-2">
            <%= form.datetime_select :publish_at %>
        </div>

        

        
        <% if form.object.persisted? %>
            <%= form.submit "Edit Tweet", class: "btn btn-primary mt-4 mb-2" %>
            <%= button_to  "Delete Tweet", tweet, method: :delete, class: "btn btn-outline-danger mt-4 mb-2", data: {'confirm': "Are you sure?"} %> 
        <% else %>
            <%= form.submit "Schedule Tweet", class: "btn btn-primary mt-4 mb-2" %>
        <% end %>
        

        
    <% end %>
</div>

app/views/tweets/_published_tweet.html.erb
<div class="card mb-3">
    <div class="card-header">
        <div class="d-flex align-items-center">
            <div class="me-auto">
                <% if published_tweet.published? %>
                <span class="badge bg-primary mb-2">Published</span>
                <% else %>
                <span class="badge bg-secondary mb-2">Unpublished</span>
                <% end %>
                <p class="fw-bold">
                    Scheduled for <%= l published_tweet.publish_at, format: :long %>
                </p>
            </div>
            <div>
                <%= image_tag published_tweet.twitter_account.image, class: "rounded-circle" %>
            </div>
            <div>
                <%= link_to  "@#{published_tweet.twitter_account.username}", "https://twitter.com/#{published_tweet.twitter_account.username}", class: "nav-link", target: :_blank %>
            </div>
        </div>
    </div>
    <div class="card-body">
        <p><%= published_tweet.body %></p>
        <% if published_tweet.published? %>  
            <%= link_to  "View Tweet", "https://twitter.com/#{published_tweet.twitter_account.username}/status/#{published_tweet.tweet_id}", class: "text-decoration-none" %>
        <% end %>      
    </div>
</div>

app/views/tweets/_tweet.html.erb
<div class="card mb-3">
    <div class="card-header">
        <div class="d-flex align-items-center">
            <div class="me-auto">
                <% if tweet.published? %>
                <span class="badge bg-primary mb-2">Published</span>
                <% else %>
                <span class="badge bg-secondary mb-2">Unpublished</span>
                <% end %>
                <p class="fw-bold">
                    Scheduled for <%= l tweet.publish_at, format: :long %>
                </p>
            </div>
            <div>
                <%= image_tag tweet.twitter_account.image, class: "rounded-circle" %>
            </div>
            <div>
                <%= link_to  "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", class: "nav-link", target: :_blank %>
            </div>
        </div>
    </div>
    <div class="card-body">
        <p><%= tweet.body %></p>
        <% if tweet.published? %>  
            <%= link_to  "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", class: "btn btn-outline-primary btn-sm", target: :_blank %>
        <% else %>
            <div class="d-flex">
                <%= link_to  "Edit Tweet", edit_tweet_path(tweet), class: "btn btn-outline-success btn-sm me-2" %>  
                <%= button_to  "Delete Tweet", tweet, method: :delete, class: "btn btn-outline-danger btn-sm", data: {confirm: "Are you sure?"} %>  
            </div>
        <% end %>   
    </div>
</div>

app/views/tweets/_unpublished_tweet.html.erb
<div class="card mb-3">
    <div class="card-header">
        <div class="d-flex align-items-center">
            <div class="me-auto">
                <% if unpublished_tweet.published? %>
                <span class="badge bg-primary mb-2">Published</span>
                <% else %>
                <span class="badge bg-secondary mb-2">Unpublished</span>
                <% end %>
                <p class="fw-bold">
                    Scheduled for <%= l unpublished_tweet.publish_at, format: :long %>
                </p>
            </div>
            <div>
                <%= image_tag unpublished_tweet.twitter_account.image, class: "rounded-circle" %>
            </div>
            <div>
                <%= link_to  "@#{unpublished_tweet.twitter_account.username}", "https://twitter.com/#{unpublished_tweet.twitter_account.username}", class: "nav-link", target: :_blank %>
            </div>
        </div>
    </div>
    <div class="card-body">
        <p><%= unpublished_tweet.body %></p>
        <% if unpublished_tweet.published? %>  
            <%= link_to  "View Tweet", "https://twitter.com/#{unpublished_tweet.twitter_account.username}/status/#{unpublished_tweet.tweet_id}", class: "text-decoration-none" %>
        <% end %>  
    </div>
</div>

app/views/tweets/edit.html.erb
<div class="d-flex align-items-center justify-content-between py-5 px-3 border rounded border-primary my-4">
    <h1>Edit Scheduled Tweets</h1>
</div>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex align-items-center justify-content-between py-5 px-3 border rounded border-primary my-4">
    <h1>Scheduled Tweets</h1>
    
    <% if Current.user.twitter_accounts.any? %>
        <%= link_to  "Add Tweet", new_tweet_path, class: "btn btn-primary" %>
    <% end %>
</div>


<div class="d-flex flex-column align-items-center justify-content-center">
<% if Current.user.twitter_accounts.none? %>
    <p class="fst-italic">You haven't linked your twitter account</p>
    <%= button_to "Connect a Twitter Account", "/auth/twitter", method: :post, data: {turbo: "false"}, class: "btn btn-primary" %>
<% end %>
</div>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="all-tab" data-bs-toggle="tab" data-bs-target="#all" type="button" role="tab" aria-controls="all" aria-selected="true">All</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="published-tab" data-bs-toggle="tab" data-bs-target="#published" type="button" role="tab" aria-controls="published" aria-selected="false">Published</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="unpublished-tab" data-bs-toggle="tab" data-bs-target="#unpublished" type="button" role="tab" aria-controls="unpublished" aria-selected="false">Unpublished</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active mt-3" id="all" role="tabpanel" aria-labelledby="all-tab"><%= render @tweets %></div>
  <div class="tab-pane fade mt-3" id="published" role="tabpanel" aria-labelledby="published-tab"><%= render @published_tweets %></div>
  <div class="tab-pane fade mt-3" id="unpublished" role="tabpanel" aria-labelledby="unpublished-tab"><%= render @unpublished_tweets %></div>
</div>

<%# <%= render @tweets %>

app/views/tweets/new.html.erb
<div class="d-flex align-items-center justify-content-between py-5 px-3 border rounded border-primary my-4">
    <h1>Schedule a Tweets</h1>
</div>

<%= render "form", tweet: @tweet %>

<p><%= Time.current.localtime %></p>

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between py-5 px-3 border rounded border-primary my-4">
    <h1>Twitter Accounts</h1>
    <%= button_to "Connect a Twitter Account", "/auth/twitter", method: :post, data: {turbo: "false"}, class: "btn btn-primary" %>
</div>

<% @twitter_accounts.each do |twitter_account| %>
    <div class="d-flex mb-4 align-items-center border rounded py-2 px-3">
        <%= image_tag twitter_account.image, class: "rounded-circle me-2" %>
        <%= link_to  "#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", class: "nav-link", target: :_blank %>
        <div class="ms-auto">
            <%= button_to "Disconnect", twitter_account, class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
    </div>
<% end %>